services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Bluebranch\BilderAlt\:
        resource: '../../../src'
        exclude: '../../../src/{Resources,DependencyInjection,Model,Tests,Migrations}'

    Bluebranch\BilderAlt\EventListener\UploadListener:
        arguments:
            - '@http_client'
        tags:
            - { name: contao.hook, hook: postUpload, method: '__invoke' }

    Bluebranch\BilderAlt\EventListener\TlSettingsCallback:
        arguments:
            - '@http_client'
        public: true

    Bluebranch\BilderAlt\EventListener\BackendTlFilesListener:
        tags:
            - { name: contao.hook, hook: loadDataContainer, method: '__invoke' }

